version: "3.8"

services:
  redis:
    image: "redis"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - intra-net
    volumes:
      - redis_data:/data

  s1:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - intra-net
      - www
    deploy:
      replicas: 3

  gateway:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "9999:80"
    depends_on:
      s1:
        condition: service_started
    restart: always
    networks:
      - www

networks:
  intra-net:
  www:

volumes:
  redis_data:
